version: '3.7'
services:
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
    expose:
      - "6379"
  frontend:
    build:
      context: ./frontend
      target: develop-stage
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend/:/frontend
    working_dir: /frontend  
    command: "npm run dev"
    tty: true
  backend:
    build:
      context: ./backend
      target: develop-stage
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8080:8080'
    volumes:
      - ./backend/:/backend
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    depends_on:
      - redis
    command: /bin/sh -c "cargo watch -x run"
volumes:
  cargo-cache:
  target-cache:
