version: '3.7'
services:
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
    expose:
      - "6379"  
  dev:
    build:
      context: ./backend
      target: "develop-starge"
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8080:8080'
    volumes:
      - './backend/:/backend'
    depends_on:
      - redis
    command: /bin/sh -c "cargo watch -x run"
