
import Head from 'next/head'
import { Button, FormLabel, HStack, Input, Table, TableCaption, TableContainer, Tbody, Td, Tfoot, Th, Thead, Tr, VStack } from '@chakra-ui/react'
import { useGetAllUrls } from 'service/get-all-urls'
import PostUrlContainer from 'container/PostUrlContainer'

export default function Home() {
  const {ret, isLoading} = useGetAllUrls()
  return (
    <>
      <Head>
        <title>rust-redis-urlshortner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>rust-redis-urlshortner</h1>
        <PostUrlContainer/>

        <TableContainer>
          <Table variant='simple'>
            <Thead>
              <Tr>
                <Th>Hash vals</Th>
                <Th>Raw urls</Th>
                <Th>Actions</Th>
              </Tr>
            </Thead>
            <Tbody>
            {ret.map((item, idx) => (
              <Tr><Td>{item.hashed}</Td><Td>{item.url}</Td><Td><Button colorScheme='blue'>Delete</Button></Td></Tr>
              ))}
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </>
  )
}
